title: Alex Koller # your name (or website title) here
logo: "/images/DSC_6825_circle.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Passionate software development graduate with a hands-on, solutions-oriented approach. Enthusiastic about developing models that solve problems. Important skills include machine learning, problem solving, programming, and creative thinking.
  <br><br>
  <a href="https://alkolhar.github.io/pdf/CV_Alex-Koller_2022-de.pdf">View My CV </a> 
  <a href="https://alkolhar.github.io/pdf/CV_Alex-Koller_2022-en.pdf"> (en)</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/koller-alex/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
